const actions = {
  STORE_CURRENT_USER: "STORE_CURRENT_USER",
  STORE_SELECTED_COLLECTION: "STORE_SELECTED_COLLECTION",
  STORE_ALL_COLLECTIONS: "STORE_ALL_COLLECTIONS",
  STORE_SELECTED_PHOTO: "STORE_SELECTED_PHOTO",
  STORE_DISPLAY_TAG: "STORE_DISPLAY_TAG",
  //   INCREMENT_PHOTO_INDEX: "INCREMENT_QUEUE_INDEX",
  //   DECREMENT _PHOTO_INDEX: "DECREMENT_QUEUE_INDEX",
  //   RESET_QUEUE: "RESET_QUEUE",
};

export default actions;
